DROP DATABASE IF EXISTS movielist;

CREATE DATABASE movielist;

USE movielist;

DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS (
  GOOGLEID VARCHAR(30) NOT NULL,
  FIRSTNAME VARCHAR(30),
  LASTNAME VARCHAR(30),
  PICURL VARCHAR(200),
  EMAIL VARCHAR(30),
  DISPLAYNAME VARCHAR(60),
  PRIMARY KEY (GOOGLEID)
);

DROP TABLE IF EXISTS SAVEDMOVIES;

CREATE TABLE SAVEDMOVIES (
  ID INT NOT NULL,
  GOOGLEID INT NOT NULL,
  MOVIEID INT NOT NULL,
  PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS MOVIES;

CREATE TABLE MOVIES (
  MOVIEID INT NOT NULL,
  TITLE VARCHAR(40),
  DESC_BODY VARCHAR(1000),
  SCORE FLOAT (1,1),
  POSTER VARCHAR(200),
  PRIMARY KEY (MOVIEID)
);

/*  Execute this file from the command line (NOT inside mysql) by typing:
 *  $ mysql -u root -p < database/schema.sql
 *  to create the database and the tables.*/