-- DROP DATABASE IF EXISTS movielist;

-- CREATE DATABASE movielist;

-- USE movielist;

-- ABOVE for local BELOW for Heroku

USE heroku_3164bae8ef63aa7;

DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS (
  GOOGLEID VARCHAR(30) NOT NULL,
  FIRSTNAME VARCHAR(30),
  LASTNAME VARCHAR(30),
  PICURL VARCHAR(200),
  EMAIL VARCHAR(30),
  DISPLAYNAME VARCHAR(60),
  PRIMARY KEY (GOOGLEID)
);

DROP TABLE IF EXISTS SAVEDMOVIES;

CREATE TABLE SAVEDMOVIES (
  ID VARCHAR(60) NOT NULL,
  GOOGLEID VARCHAR(60) NOT NULL,
  MOVIEID VARCHAR(60) NOT NULL,
  PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS MOVIES;

CREATE TABLE MOVIES (
  MOVIEID INT NOT NULL,
  TITLE VARCHAR(40),
  DESC_BODY VARCHAR(1000),
  SCORE VARCHAR(5),
  POSTER VARCHAR(200),
  PRIMARY KEY (MOVIEID)
);

/*  Execute this file from the command line (NOT inside mysql) by typing:
 *  $ mysql -u root -p < database/schema.sql
 *  to create the database and the tables.*/